# Generated by Django 3.1.7 on 2021-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
